
<input type="hidden" id="controller" value="<?php echo $controller; ?>">
<input type="hidden" id="action" value="<?php echo $action; ?>">
<input type="hidden" id="url" value="<?php echo $url; ?>">
<input type="hidden" id="title" value="<?php echo $title; ?>">
<input type="hidden" id="geographic_uf" value="<?php echo isset($uf) ? $uf : ''; ?>">
<input type="hidden" id="geographic_city" value="<?php echo isset($city) ? $city : ''; ?>">
<input type="hidden" id="geographic_hood" value="<?php echo isset($hood) ? $hood : ''; ?>">
<input type="hidden" id="geographic_street" value="<?php echo isset($street) ? $street : ''; ?>">
<input type="hidden" id="geographic_number" value="<?php echo isset($number) ? $number : ''; ?>">
<input type="hidden" id="geographic_lat" value="<?php echo isset($lat) ? $lat : ''; ?>">
<input type="hidden" id="geographic_lng" value="<?php echo isset($lng) ? $lng : ''; ?>">